# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class K8sResourceCli < Formula
  desc "CLI tool to retrieve resource requests and usage metrics for Kubernetes deployments and cronjobs"
  homepage "https://github.com/madeddie/k8s-resource-cli"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/madeddie/k8s-resource-cli/releases/download/v0.2.2/k8s-resource-cli_0.2.2_darwin_amd64.tar.gz"
      sha256 "b4bd0b54aff87e98da0b518ca7a75e7e8f2bc95601f98e4032716f41e59efbb2"

      define_method(:install) do
        bin.install "k8s-resource-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/madeddie/k8s-resource-cli/releases/download/v0.2.2/k8s-resource-cli_0.2.2_darwin_arm64.tar.gz"
      sha256 "53a16221d5a4a73e77daed0286d5b4622138ae26e0d88053c1e58ad4303808b2"

      define_method(:install) do
        bin.install "k8s-resource-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/madeddie/k8s-resource-cli/releases/download/v0.2.2/k8s-resource-cli_0.2.2_linux_amd64.tar.gz"
      sha256 "4c0e077d76fb3f80867036881edf19915832229788b416831c5366484455550a"
      define_method(:install) do
        bin.install "k8s-resource-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/madeddie/k8s-resource-cli/releases/download/v0.2.2/k8s-resource-cli_0.2.2_linux_arm64.tar.gz"
      sha256 "a1cb8bc728d022054cf17b56127e93cea100486c35dc49d780342498afda7e1f"
      define_method(:install) do
        bin.install "k8s-resource-cli"
      end
    end
  end

  test do
    system "#{bin}/k8s-resource-cli", "--version"
  end
end
