# This file was generated by GoReleaser. DO NOT EDIT.
cask "k8s-resource-cli" do
  version "0.2.4"

  on_macos do
    on_intel do
      sha256 "762b0eded8443bfd6cbdbdba5aefc327fc90043f4dd034b2d4e3185e1cdba573"
      url "https://github.com/madeddie/k8s-resource-cli/releases/download/v#{version}/k8s-resource-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5472bb4927a43b1072981b3c9f6411c6e0257b9dded50df0fe7aed3c4b0a3820"
      url "https://github.com/madeddie/k8s-resource-cli/releases/download/v#{version}/k8s-resource-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "30d8b6b2f80364885b976f0f3797be306c5577a6dbd57f3934e5494a9b4a04ad"
      url "https://github.com/madeddie/k8s-resource-cli/releases/download/v#{version}/k8s-resource-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2a898bf1bd0816cceac223f159c8d3d6509887b3ab8b99c9f3c255a64f80af66"
      url "https://github.com/madeddie/k8s-resource-cli/releases/download/v#{version}/k8s-resource-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "k8s-resource-cli"
  desc "CLI tool to retrieve resource requests and usage metrics for Kubernetes deployments and cronjobs"
  homepage "https://github.com/madeddie/k8s-resource-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "k8s-resource-cli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/k8s-resource-cli"]
    end
  end

  # No zap stanza required

end
