# This file was generated by GoReleaser. DO NOT EDIT.
cask "k8s-resource-cli" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "91e8232784d0abf9399583d38a6394cb3c91abaefc52943395de870adc49b7c0"
      url "https://github.com/madeddie/k8s-resource-cli/releases/download/v#{version}/k8s-resource-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a527f7f28acb871521ca9f91fdc4ea8d10c2a8b24bb5254558099099f3396126"
      url "https://github.com/madeddie/k8s-resource-cli/releases/download/v#{version}/k8s-resource-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6b62d6428761adf7f1ce77d82ba51bb0b6e5fc75e1fd5d8774b606feb051d9f7"
      url "https://github.com/madeddie/k8s-resource-cli/releases/download/v#{version}/k8s-resource-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "76eaaf2eaea7eb954aac806f360402df01f0029448a585c7aa7dbd816c886026"
      url "https://github.com/madeddie/k8s-resource-cli/releases/download/v#{version}/k8s-resource-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "k8s-resource-cli"
  desc "CLI tool to retrieve resource requests and usage metrics for Kubernetes deployments and cronjobs"
  homepage "https://github.com/madeddie/k8s-resource-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "k8s-resource-cli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/k8s-resource-cli"]
    end
  end

  # No zap stanza required

end
