# This file was generated by GoReleaser. DO NOT EDIT.
cask "k8s-resource-cli" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/k8s-resource-cli"]
    end
  end

  version "0.4.2"

  on_macos do
    on_arm do
      sha256 "41ed790600b82c95d9d66fc60af52e9b26f229b9dfce66ad71147dfcfef94d15"
      url "https://github.com/madeddie/k8s-resource-cli/releases/download/v#{version}/k8s-resource-cli_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "11dbf9d44947bb5eddd5d8ccb6f92ef49803c66e64282dfb7fcc277941d40c2a"
      url "https://github.com/madeddie/k8s-resource-cli/releases/download/v#{version}/k8s-resource-cli_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "77cdf1b2c9751de8c98adafb05c46340da4122d61969bf76f4b10a7d2611433b"
      url "https://github.com/madeddie/k8s-resource-cli/releases/download/v#{version}/k8s-resource-cli_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0154a593be771bbe3d2edf9b504826b1be9475d5da64e2f34804e6e26f6860f4"
      url "https://github.com/madeddie/k8s-resource-cli/releases/download/v#{version}/k8s-resource-cli_#{version}_linux_amd64.tar.gz"
    end
  end

  name "k8s-resource-cli"
  desc "CLI tool to retrieve resource requests and usage metrics for Kubernetes deployments and cronjobs"
  homepage "https://github.com/madeddie/k8s-resource-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "k8s-resource-cli"

  # No zap stanza required
end
